# Generated by Django 4.2.13 on 2024-07-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
