# Generated by Django 4.2.13 on 2024-06-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="no_imag.png", upload_to="recipes/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
